import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=''> 
          <p className='flex flex-col items-center '>
            Get started by editing&nbsp;
            <code className='text-title-1 text-primary-blue font-title-1 uppercase'>pages/index.tsx</code>
          </p>
      </main>
    </>
  );
}
