import Head from 'next/head';
import Footer from '../components/Footer';
import Header from '../components/Header';
export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="bg-white">
        <h1>Home1</h1>
      </main>
      <Footer />
    </>
  );
}
